### ISSUE TITLE
 Kite status bar text disappears when disabling and re-enabling from preferences

### ISSUE THREAD

**Issue by jsbautista** [spyder-ide/spyder-kite#2]
### **What steps will reproduce the problem?**

 Kite icon disappears from the status bar when enabling and disabling from preferences
![KiteStatusBar](https://github.com/spyder-ide/kite-provider/assets/42411448/e72d0e29-4c81-472d-891c-6c5f9bc0a625)

**Comment by dalthviz** [comment]
Note: Seems like when disabling the provider, the logic inside the client `stop` method is not setting `thread_started` to `False` 

https://github.com/spyder-ide/kite-provider/blob/b0e9c978052827aae7f2085042c7e6fa4cd0d4f1/kite_provider/client.py#L72-L76

That prevents starting the thread that handles the connection with Kite when the provider is enabled again:

https://github.com/spyder-ide/kite-provider/blob/b0e9c978052827aae7f2085042c7e6fa4cd0d4f1/kite_provider/client.py#L61-L65

**Comment by dalthviz** [comment]
Note: Also, related with the enable/disable providers behavior see https://github.com/spyder-ide/spyder/issues/21462
