### ISSUE TITLE
Text overwrite when accepting completion from kite

### ISSUE THREAD

**Issue by jsbautista** [spyder-ide/spyder-kite#3]
### **What steps will reproduce the problem?**
When giving completed sometimes kite overwrites part of what had been written
![KiteDeleteCharacters](https://github.com/spyder-ide/kite-provider/assets/42411448/44def7f8-131d-442f-a292-9f473d2f6feb)

**Comment by jsbautista** [comment]
This error can be avoided by changing CRLF (windows) to LF (linux) in the "convert end-of-line characters" option in the "source" menu.
![KiteDeleteCharactersLF](https://github.com/spyder-ide/kite-provider/assets/42411448/57b4b9a4-3b47-4e12-aa2a-6fec27731b5d)

**Comment by dalthviz** [comment]
Reopening to close it when merging #13
