### ISSUE TITLE
Kite not working on some files

### ISSUE THREAD

**Issue by jsbautista** [spyder-ide/spyder-kite#4]
### **What steps will reproduce the problem?**
Kite Copilot doesn't seem to register that Spyder is installed. Can't get results from Kite with "welcome file" or "temporary files"

![KiteWelcomeFile](https://github.com/spyder-ide/kite-provider/assets/42411448/ae77a23f-2c13-4474-b297-e98f540a719c)

**Comment by jsbautista** [comment]
This error can be avoided by changing CRLF (windows) to LF (linux) in the "convert end-of-line characters" option in the "source" menu.
![KiteWelcomeFilelf](https://github.com/spyder-ide/kite-provider/assets/42411448/d5142856-0d18-410f-b739-196d704ab648)

**Comment by dalthviz** [comment]
Reopening to close it when merging https://github.com/spyder-ide/kite-provider/pull/13
